export type DiagnosticSeverity = "warning" | "error";

export type DiagnosticCode =
  | "NOT_IMPLEMENTED"
  | "INPUT_LIMIT_EXCEEDED"
  | "MALFORMED_INPUT"
  | "JPEG_INVALID_SOI"
  | "JPEG_INVALID_MARKER"
  | "JPEG_TRUNCATED_MARKER"
  | "JPEG_TRUNCATED_SEGMENT_LENGTH"
  | "JPEG_INVALID_SEGMENT_LENGTH"
  | "JPEG_TRUNCATED_SEGMENT"
  | "JPEG_TRUNCATED_SCAN"
  | "JPEG_MISSING_EOI"
  | "JPEG_SEGMENT_LIMIT_EXCEEDED"
  | "JPEG_TRAILING_DATA"
  | "WEBP_INVALID_RIFF_HEADER"
  | "WEBP_INVALID_RIFF_SIZE"
  | "WEBP_TRUNCATED_RIFF"
  | "WEBP_TRUNCATED_CHUNK_HEADER"
  | "WEBP_TRUNCATED_CHUNK"
  | "WEBP_CHUNK_LIMIT_EXCEEDED"
  | "WEBP_INVALID_PADDING"
  | "WEBP_INVALID_VP8X"
  | "WEBP_DUPLICATE_VP8X"
  | "WEBP_INCONSISTENT_FEATURE_FLAGS"
  | "WEBP_TRAILING_DATA"
  | "TIFF_TRUNCATED_HEADER"
  | "TIFF_INVALID_BYTE_ORDER"
  | "TIFF_INVALID_MAGIC"
  | "TIFF_INVALID_FIRST_IFD_OFFSET"
  | "TIFF_TRUNCATED_IFD"
  | "TIFF_IFD_ENTRY_LIMIT_EXCEEDED"
  | "TIFF_IFD_DEPTH_LIMIT_EXCEEDED"
  | "TIFF_TRAVERSAL_LIMIT_EXCEEDED"
  | "TIFF_CYCLIC_IFD"
  | "TIFF_UNSUPPORTED_FIELD_TYPE"
  | "TIFF_INVALID_VALUE_RANGE"
  | "TIFF_INVALID_VALUE_OFFSET"
  | "TIFF_INVALID_POINTER"
  | "TIFF_INVALID_RATIONAL";

export interface Diagnostic {
  readonly severity: DiagnosticSeverity;
  readonly code: DiagnosticCode;
  readonly message: string;
  readonly offset?: number;
}
